language: ruby
rvm:
  - 1.9.3-p392
env:
  - DB=mysql GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
services:
  - elasticsearch
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq aspell aspell-en libaspell-dev
script:
  - bundle exec rake
bundler_args: --without=development
branches:
  except:
    - release
notifications:
  email: false
