base:
  format:
    service_manual_guide: 0.3
    service_manual_topic: 0.3
    transaction: 1.5
    # Should appear below govuk (mainstream) content
    aaib_report: 0.2
    dfid_research_output: 0.2
    hmrc_manual_section: 0.2
    service_standard_report: 0.05
    # Inside Gov formats
    contact: 0.3
    document_collection: 1.3
    document_series: 1.3
    minister: 1.7
    operational_field: 1.5
    organisation: 2.5
    topic: 1.5
    topical_event: 1.5
    # Hide mainstream browse pages
    mainstream_browse_page: 0
    # Topics
    specialist_sector: 2.5
  content_store_document_type:
    answer: 3.75
    contact: 2.5
    detailed_guide: 2.5
    document_collection: 2.5
    foi_release: 0.2
    form: 2.5
    guidance: 2.5
    guide: 3.75
    licence: 2.5
    local_transaction: 2.5
    manual: 2.5
    map: 2.5
    place: 3.75
    promotional: 2.5
    regulation: 2.5
    simple_smart_answer: 3.75
    smart_answer: 3.75
    statutory_guidance: 2.5
    transaction: 3.75
    travel_advice_index: 1.5
    travel_advice: 3.75
  organisation_state:
    closed: 0.2
    devolved: 0.3
  is_historic:
    true: 0.5
# Overrides to apply to the sitemap priorities in external search
external_search:
  format:
    mainstream_browse_page: 2
    policy: 1.5
    topic: 2
